### ISSUE TITLE
Why exclude vim files from auto hexmode?

### ISSUE THREAD

**Issue by chaoren** [fidian/hexmode#10]
See https://github.com/fidian/hexmode/blob/14a4795743cada3bca743f54cf000e33141a2f9f/plugin/hexmode.vim#L57.

Why? What if a vim plugin supplies binary data?

**Comment by chaoren** [comment]
This confused me a bit when trying to test my changes by creating and editing files next to hexmode.vim. Though, I don't think a regular user would ever run into this.

**Comment by chaoren** [comment]
Looks like it came from the comment here: http://vim.wikia.com/wiki/VimTip1518. I wonder if it still applies.

**Comment by fidian** [comment]
I appreciate that you tracked down the source of the code and documented it in this ticket.  Thanks for the fixed code and thanks even more for linking to the page that inspired the original code.
