### ISSUE TITLE
.vimrc now with ft=xxd, opening in hexmode

### ISSUE THREAD

**Issue by oblitum** [fidian/hexmode#22]
After the last commit when I open my `~/.vimrc` file with `vim ~/.vimrc` it's open in hexmode, and the filetype is `xxd`. Disabling the plugin fix the issue.

**Comment by chaoren** [comment]
Would you mind sharing your .vimrc? I suspect you have some special characters in there that causes the plugin to think it's a binary file.

**Comment by chaoren** [comment]
Though I would rather suggest the maintainer to just get rid of [this](https://github.com/fidian/hexmode/blob/7a1610faa03afc3aeb3b58fedec8bf08a0cdc772/plugin/hexmode.vim#L73) and all similar tricks so the plugin can behave more predictably. We can always add more binary patterns [here](https://github.com/fidian/hexmode/blob/7a1610faa03afc3aeb3b58fedec8bf08a0cdc772/plugin/hexmode.vim#L15), and the user can always manually open a file with `vim -b <file>`.

**Comment by oblitum** [comment]
@chaoren https://github.com/oblitum/dotfiles/blob/56d4dceba6c5b5a1e06159b7f243959759908096/.vimrc. I have special chars at https://github.com/oblitum/dotfiles/blob/56d4dceba6c5b5a1e06159b7f243959759908096/.vimrc#L158-L159, they can't be viewed on GitHub.

**Comment by oblitum** [comment]
@chaoren I still need to change raw escapes to https://groups.google.com/forum/#!msg/vim_dev/JLp01xUC7v0/QJoKSfxBBwAJ

**Comment by oblitum** [comment]
yep, changing from using raw escapes for that two lines to:

```vim
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

solves the issue with hexmode. But I still think Hexmode heuristics are a bit loose.

**Comment by fidian** [comment]
I'm glad that there's a workaround for this issue. I'm going to close it and have opened one that addresses @chaoren's comments and tackles the issue a bit more accurately.
