### ISSUE TITLE
DISCUSSION: Removal of automatic binary file detection?

### ISSUE THREAD

**Issue by fidian** [fidian/hexmode#23]
Right now we use automatic binary file detection in order to enable hex mode. One can also use `vim -b` or detect hexmode by file extension. Lastly, one may turn it on by `ToggleHex`.

* Automatic detection is simpler to use but causes confusing behavior. For instance, issue #22 was created because the user had a binary-ish character in an otherwise text file.
* Using `-b` has no issues except that the user may need to remember to use that flag when starting `vim`.
* Detecting binary files by extension is a nuisance to maintain because the list of extensions should list the majority of binary files that people edit. Also, it is more likely that other plugins would conflict with hexmode if, for example, you had a plugin that would let you edit `.zip` files and extract individual file contents.

This issue was created as a response to #22, where the automatic hex editing of a file caused issues. The source of this came from the pull request #7, which I thought was a brilliant idea. Unfortunately, that has been tweaked in #9, #11, and I suspect #13. This means the feature is brittle or causes problems.

Proposal:

* The auto detection code remains, but is disabled and can be enabled with a flag.
* The binary file detection based on extensions remains.

For discussion:

* Should the file extension detection be likewise disabled and enabled with a flag? I'm undecided.
* My lack of any skills whatsoever with VimScript. I don't think I'm comfortable making this change seeing how I've not made many bug-free commits to this repository.

I would love to get feedback from @chaoren and anyone else. This ticket will stay open for at least two weeks in order to collect feedback.

**Comment by chaoren** [comment]
> Should the file extension detection be likewise disabled and enabled with a flag? I'm undecided.

It kind of is already. You can override the list of extensions with an empty list.

> My lack of any skills whatsoever with VimScript. I don't think I'm comfortable making this change seeing how I've not made many bug-free commits to this repository.

I volunteer as tribute.

**Comment by fidian** [comment]
>> Should the file extension detection be likewise disabled and enabled with a flag? I'm undecided.
>
> It kid of is already. You can override the list of extensions with an empty list.

That's true, but I meant to ask if we should disable the file extension detection entirely by default and enable it when the user specifically says they want it, similar to how the auto detection code should be disabled by default.

I'm a fan of consistency, which says to disable the auto detection and disable the extension detection. However, I'm also a fan of backwards compatibility so that means to keep the file extension detection working as-is. My question is if we should be consistent and disable all of the automatic things or if we should continue the extension based detection as it has always been done.

> I volunteer as tribute.

Thank you! I was strongly wishing you would help with this. If you make the pull request now and link it to this issue, people would have the time to review it and comment on that as well.

**Comment by chaoren** [comment]
> That's true, but I meant to ask if we should disable the file extension detection entirely by default and enable it when the user specifically says they want it, similar to how the auto detection code should be disabled by default.

To be honest, I never rely on the file extension detection either. I always manually invoke vim with `-b` whenever I need to edit a binary file. However, the file extension detection has caused way less trouble than the content-based detection. The implementation is simple and there are very few surprises. Even if a certain extension happen to conflict with another plugin (e.g., a terminal image viewer for .jpg files), then it'll still be super easy to diagnose and fix (by removing that extension).

I guess it ultimately comes down to user consensus. If most users find it useless like me, then the default list is better off empty, and they can set whatever extensions they want.

**Comment by oblitum** [comment]
The content based automatic file detection is unreliable and should be removed. For example, I tried to open a PDF file, which is full of special chars and it opened in Hexmode...

**Comment by fidian** [comment]
@oblitum, what would you have expected to happen when you edit a PDF in vim?

**Comment by oblitum** [comment]
@fidian I'd like to see it in hexadecimal only if I find it necessary. PDF can contain binary sections, but it's not all binary, it contains structure that's better visualized in plain text.

**Comment by fidian** [comment]
@oblitum Thanks for that feedback, it is very useful. Would you want to install the plugin and have it automatically edit files in hex based on file extension or would you think that using `vim -b` or the `ToggleHex` command is good enough?

I'm asking about the above questions because it looks like even if automatic file type detection is disabled, PDF files would still be opened as hex: https://github.com/fidian/hexmode/blob/master/plugin/hexmode.vim#L15

**Comment by oblitum** [comment]
@fidian I'd just remove pdf from that list and keep it short as possible. I'd be OK to call `ToogleHex` myself, it's what I expect from most plugins I consider good, that it just documents in help/readme that one should set an autocommand like in the example, to have Hexmode executed automatically.

**Comment by chaoren** [comment]
@oblitum There's a `g:hexmode_patterns` variable that you can set. It's in the [vim doc](https://github.com/fidian/hexmode/blob/17017e3429b3a89fc5cf82eb77413b270d20d70b/doc/hexmode.txt#L49), but not in the README. Though it should probably be documented in both places, since nowadays people just read the github page.

**Comment by oblitum** [comment]
Ops, got Hexmode in a simple IRC log file.... It's all over now.

**Comment by fidian** [comment]
@oblitum Does chaoren's branch work for you? If you test it out, I will be able to have more confidence in merging it.

@chaoren If I asked you to also remove all file extensions, but provide documentation for how to set up a good, standard list of file extensions, would you be willing to do that on your fork? I'm thinking that we present options for turning it on automatically or binding to a key or something, but disable all of the automatic stuff except `vim -b`.

**Comment by chaoren** [comment]
@fidian 

> good, standard list of file extensions

I don't think such a thing exists. It's going to be different for everyone. `g:hexmode_patterns` is there for the user to set whatever extension they like. Though honestly, I think most people would just use `vim -b` if they knew about it.

**Comment by chaoren** [comment]
> If I asked you to also remove all file extensions, but provide documentation for how to set up a good, standard list of file extensions, would you be willing to do that on your fork?

Done.

**Comment by oblitum** [comment]
> @oblitum Does chaoren's branch work for you? If you test it out, I will be able to have more confidence in merging it.

I've reviewed the pull and it's fine for me.

**Comment by fidian** [comment]
Merged #24. Closing this discussion.
