### ISSUE TITLE
DOS line endings

### ISSUE THREAD

**Issue by rolf007** [fidian/hexmode#29]
Hi,
When opening a file with DOS line endings, (CR LF = 0d 0a) and switching back and forth to/from hex mode, an extra CR is inserted before every CR LF.
This can be fixed by moving "silent %!xxd -r" to after "let &l:bin = b:oldbin".

**Comment by fidian** [comment]
I'm awful at understanding vimscript. Can you explain how this would fix the problem or provide useful links? I can't seem to find anything on the net that breaks it down for a simpleton like myself.

I didn't write the plugin and only wanted a place where people could contribute patches for a really useful tool for vim. The end result is that I often make changes in the script and have to back them out later because it causes unintended side effects. To date, I don't think I have had a successful commit in the repository that I wrote myself. :-)

**Comment by chaoren** [comment]
From the docs:
```
'binary' 'bin'		boolean	(default off)
			local to buffer
			{not in Vi}
	This option should be set before editing a binary file.  You can also
	use the |-b| Vim argument.  When this option is switched on a few
	options will be changed (also when it already was on):
		'textwidth'  will be set to 0
		'wrapmargin' will be set to 0
		'modeline'   will be off
		'expandtab'  will be off
	Also, 'fileformat' and 'fileformats' options will not be used, the
	file is read and written like 'fileformat' was "unix" (a single <NL>
	separates lines).
	The 'fileencoding' and 'fileencodings' options will not be used, the
	file is read without conversion.
	NOTE: When you start editing a(nother) file while the 'bin' option is
	on, settings from autocommands may change the settings again (e.g.,
	'textwidth'), causing trouble when editing.  You might want to set
	'bin' again when the file has been loaded.
	The previous values of these options are remembered and restored when
	'bin' is switched from on to off.  Each buffer has its own set of
	saved option values.
	To edit a file with 'binary' set you can use the |++bin| argument.
	This avoids you have to do ":set bin", which would have effect for all
	files you edit.
	When writing a file the <EOL> for the last line is only written if
	there was one in the original file (normally Vim appends an <EOL> to
	the last line if there is none; this would make the file longer).  See
	the 'endofline' option.
```
Here's the reason:
> **the file is read and written like 'fileformat' was "unix" (a single `<NL>` separates lines)**

The suggested fix seems correct.

**Comment by fidian** [comment]
Just merged the code from @chaoren, which should address this issue. If not, feel free to reopen or submit a new issue.

Thanks again @chaoren, I appreciate your help. I missed that portion and instead got hung up on the "should be set before editing a binary file," which I thought could mean that we want this to be a binary file before we enable the option.
