### ISSUE TITLE
CONVERSION ERROR when using `g:hexmode_autodetect`

### ISSUE THREAD

**Issue by mjsir911** [fidian/hexmode#31]
When I open a binary file with the `-b` flag, everything seems to work normally

``` bash
$ cp $(which test) .
$ vim -b -c ":wq" test
<opens file and writes/closes file with no problem>
$ ./test
<no error>
```

When I open a file with `let g:hexmode_autodetect = 1` though it mangles the binary file
``` bash
$ cp $(which test) .
$ vim -c 'let g:hexmode_autodetect = 1' -c ":wq" test
```
At this point, I get this output inside vim
```
"test" [noeol][converted] 49L, 24857C
"test"  CONVERSION ERROR in line 31;[noeol] 49L, 22379C written
Save changes to "test"?
[Y]es, (N)o, (C)ancel: 
```
If I press `Y`, it does not quit and puts my inside the editor with hexmode enabled
If I press `N`, it quits successfully, but the executable cannot run anymore

```bash
$ ./test 
Killed: 9
```

This is almost definitely do to some vim configuration either shipped on my system, or configured by me

``` bash
$ cp $(which test) .
$ vim -c 'let g:hexmode_autodetect = 1' -c ":wq" -u NONE test
<works without error>
$ ./test
<no error>
```

I think this is something to do with the `[converted]` flag as seen in the vim output above. I'm not sure if this is something that you can do inside of the hexmode script, or just something you need to put in the docs warning about.

**Comment by chaoren** [comment]
> This is almost definitely do to some vim configuration either shipped on my system, or configured by me

Nope. I can reproduce too. It's weird, the only difference between editing with `-b` and editing with auto detect seems to be the `binary` setting, but even setting that for auto detect doesn't fix the issue.

**Comment by mjsir911** [comment]
So setting binary mode in a `BufReadPre` would fix the problem. Unfortunately the `search` call [here](https://github.com/fidian/hexmode/blob/7b2872c1598e10ae8ad0819a76839a453e35c986/plugin/hexmode.vim#L85) would not work due to the problems outlined in the commit 7a1610faa03afc3aeb3b58fedec8bf08a0cdc772.

Something could be done on the filename during a `BufReadPre` to determine if the file is binary before loading it into the buffer, but that has problems too: 001aafaa9dca0869b33c0025899a7c007c0c74c1.

Unless there is some autocmd before vim does `[conversion]` stuff but after it loads the file into the buffer, I'm not sure where to proceed.

**Comment by mjsir911** [comment]
Quick and dirty fix, but I don't seem to be having any problems with a `system()` call in an `BufReadPre`

I have a fix in commit 83e39821c7cf103d1cfde87c304f570993d8d906 but I'm not sure if I should make a PR because `system()` in an autocmd has been a problem(#17)

**Comment by fidian** [comment]
The difference in the two files is an extra newline appended in the one that's broken. Removing the newline restores the file to the right contents.

I suppose we have the following options. Please chime in if you see more.

* Support the auto detection code
    * Start putting `system()` calls in the codebase again. :-(
    * Find an alternate way to detect if a file is binary automatically other than `search()` and `system()`.
* Partially support auto detection code
    * Document problems with the auto detection code
* Remove the auto detection code
    * Can remove it but preserve the behavior with file extensions.
    * Remove auto detection and file extension checks entirely and let the user configure Vim however they want manually.

If that's the list of options we see, I'm in favor of the partial support and calling out exactly what's going wrong and why, but I really would love other viewpoints.

**Comment by mjsir911** [comment]
### Full support
I don't think there's going to be an alternative to `system()` for checking if the file is binary during `BufReadPre`... and it seems there were problems with using the `system()` call so unless that problem has been solved (which it seems to be for me), I would suggest avoiding auto detection code.

### Partial support
I would definitely oppose partial auto detection support, as I have not seen successful saving on files without the explicit `-b` flag, which sort of defeats the point of auto detection. 

I would still support the `g:hexmode_patterns` though, as that seems to be working fine, although a simple alternative I can think of is just dropping `setlocal binary` in `~/.vim/ftplugin/pdf.vim` and not worry about that.

### No support
I think dropping auto detection should be the way to go if full support cannot be done in a reliable way. I've opted for a couple lines in my vimrc to do the same thing. 


``` vim
autocmd BufReadPre *
  \ let file = system("file --mime -b -L " . shellescape(expand("%:p"))) |
  \ if file =~# "charset=binary" &&  file !~# "text/.*;" |
  \   setlocal binary |
  \ endif
```

It would be simple to implement inside the hexmode plugin, but the code might have some problems and I'm not sure if the hexmode plugin is the right place for it

**Comment by fidian** [comment]
I don't know if this is actually a problem. First, here's my starting point before each example.

    11:54 cajun:~$ cp `which test` test
    11:54 cajun:~$ md5sum test
    dbadc02014945f8e5f4ada8d76ddc366  test
    11:54 cajun:~$ ll test
    -rwxr-xr-x 1 fidian fidian 47824 Oct 17 11:54 test*

With that in place, I ran the following.

    11:55 cajun:~$ vim -c 'let g:hexmode_autodetect = 1' -c ":wq" test
    11:55 cajun:~$ md5sum test
    6a571b88dfeeb7c03ca5174d790a1b18  test
    11:56 cajun:~$ ll test
    -rwxr-xr-x 1 fidian fidian 47825 Oct 17 11:55 test*

Yes, it modified the file. However, if you get rid of the `-c ":wq"` bit, you will see something.

![screenshot from 2017-10-17 11-57-16](https://user-images.githubusercontent.com/428348/31678013-6057c5cc-b332-11e7-80ac-2e8356b46e83.png)

It is not in hexmode. So that newline at the end is pretty much what I would expect when you are not editing a file in binary.  Further proof:

    11:58 cajun:~$ cp `which test` test
    11:58 cajun:~$ vim -u NONE -c ":wq" test
    11:58 cajun:~$ md5sum test
    6a571b88dfeeb7c03ca5174d790a1b18  test
    11:58 cajun:~$ ll test
    -rwxr-xr-x 1 fidian fidian 47825 Oct 17 11:58 test*
    11:58 cajun:~$ cp `which test` test
    11:59 cajun:~$ vim -u NONE -b -c ":wq" test
    11:59 cajun:~$ md5sum test
    dbadc02014945f8e5f4ada8d76ddc366  test
    11:59 cajun:~$ ll test
    -rwxr-xr-x 1 fidian fidian 47824 Oct 17 11:59 test*

The problem you are reporting is just `vim` editing a binary file and saving it like a text file.

I will have to open another issue for a problem I found while testing the above cases.

@mjsir911 - For now, do you agree and this issue should be closed?

**Comment by fidian** [comment]
While I was writing #35, I think that maybe the problems could be related, depending on your configuration. The difference I have is `--cmd` executes right away and `-c` executes later, so using `-c 'let g:hexmode_autodetect = 1` didn't have any effect on `vim` and it operates the same with and without the hexmode plugin.

With #35, I force the plugin to be enabled earlier with `--cmd`, but it experiences the same symptoms that you were reporting with regards to a newline at the beginning. There's an additional problem about it corrupting the file (which is awful), but that issue can be tackled in #35 exclusively. Maybe there should be some sort of command added to `BufReadPost` that reads the file again after HexMode is enabled?

**Comment by mjsir911** [comment]
I can duplicate your results with editing vim without the hexmode plugin at all. The behaviour vim seems to show is converting the file when not opened as a binary file.

I think the issue is that when editing a file with hexmode autodetection enabled, I expect the file to save with the changes I've made, and if I haven't made any changes then the file should not change.

This may be a limitation of vim, but in which case I consider `g:hexmode_autodetect` useless, as it does not work.

**Comment by mjsir911** [comment]
I took a look into reading the file again after hexmode is enabled and after the buffer is loaded, and it seems that if I open a binary file with no `-b` flag and then `:%!xxd %`, it does load the file without a newline at the end. 

This could be a potential solution to autoloading binary files, because the file could be set to binary during the `BufReadPost` autocommand and the buffer will not be mangled

**Comment by mjsir911** [comment]
Some tests here
``` bash
$ cp $(which ls) .
$ shasum ls; vim -u NONE --noplugin ls +'wq!'; shasum ls 
# ^^^ Different hash
$ rm ls

$ cp $(which ls) .
$ shasum ls; vim -u NONE --noplugin ls +'%!xxd' +'%!xxd -r' +'wq!'; shasum ls 
# ^^^ Different hash, same hash as above
$ rm ls

$ cp $(which ls) .
$ shasum ls; vim -u NONE --noplugin ls +'%!xxd %' +'%!xxd -r' +'wq!'; shasum ls 
# ^^^ Different hash, different hash as above, this time I try `%!xxd %` instead of `%!xxd`
$ rm ls

$ cp $(which ls) .
$ shasum ls; vim -u NONE --noplugin ls +'set bin' +'%!xxd' +'%!xxd -r' +'wq!'; shasum ls 
# ^^^ same hash. Does `set bin` run before or after buffer is loaded? I assume after.
# This command works as expected. What's going on?
$ rm ls
```

I have a sneaking suspicion that binary mode just has to be set on the save, not before the load.

I thought I already tested that and it didn't work, but the results above show that if you `set bin` that you will get the same file. 

I'm a bit confused, but I'll try putting together a fix to set binary mode on save if `s:IsHexmodeEditable` and see if that does anything.

**Comment by fidian** [comment]
I am starting to wonder if this is a bug in the plugin or if it is related to vim. Maybe a bug or maybe just how we're using vim. Or maybe I don't understand the bug clearly enough. Here's what I think:

* Vim opens the file in text mode.
* Newline is added.
* Autodetect kicks in
    * Set binary flag
    * Pass through xxd
* File is saved
    * Passed through xxd

Is it as simple as us not using `vim -b` on binary files and expecting it to work? Maybe our base assumptions are wrong.

**Comment by mjsir911** [comment]
I think you are right, but just to elaborate a bit:
`autocmd BufReadPre` is getting executed before newline is added
if binary mode is set during `BufReadPre`, the newline will not be added
`autocmd BufReadPost` is getting executed after newline is added

A potential fix is detecting the filetype somehow during `BufReadPre`, but all I've come up with is through `system()` calls and there may be [problems](https://github.com/fidian/hexmode/issues/17) with that. 

At this point, I would propose to disable autodetection features as I believe at the current state they do more harm than good, with users believing they can safely edit their binary files only to find out that the file was changed in unexpected ways.

Or at least put big scary warnings saying that this behaviour is unstable.

**Comment by fidian** [comment]
First off, I'll just put out there that I'm awful with vimscript, but at least I'm a programmer. With that in mind, maybe we could just detect the file size or copy the buffer or something in `BufReadPre`, then fix things in `BufReadPost`?  Something along these lines. Remeber, I don't know vimscript.

    BufReadPre:
        size = getSize()

    BufReadPost:
        if (we should enable binary mode)
            enable binary mode
            if (getSize() > size)
                trim (getSize() - size) bytes from end

What I don't know is why the buffer is messed up as well in the middle as was seen in #35. I'm curious to see if these problems are related because, if they are, then the size detected in `BufReadPre` will be a larger value than what's detected in `BufReadPost`.

Do you foresee any problems with this? I'm willing to to learn vimscript in order to help manage this plugin.

**Comment by fidian** [comment]
I've taken the advice of removing autodetection code. If it can be made into a stable feature that also addresses the same slew of problems that were experienced earlier, I would be happy to add it back in.
