### ISSUE TITLE
hash tests don't work on OSX

### ISSUE THREAD

**Issue by mjsir911** [fidian/hexmode#32]
``` bash
$ bash test
...
Edit a tar file as binary. Tar plugin should win, no hex should be shown.
Press enter to continue.



A binary file doesn't change when saved ... test: line 47: md5sum: command not found
test: line 49: md5sum: command not found
pass
An auto-detected binary file doesn't change when saved ... test: line 54: md5sum: command not found
test: line 56: md5sum: command not found
pass
```
On my mac the md5 command is `md5` as opposed to `md5sum`

It also passes the tests when there are errors

**Comment by fidian** [comment]
Let's split this into two issues.

The first problem is using `md5sum` (Linux and variants) as opposed to `md5` (MacOS). I could switch to using `shasum -a 256`, which is on both systems, but instead I picked `diff` in the latest commit. Would you see if that works?

Secondly, the testing does pass the tests when there are errors. I'm not smart enough when it comes to Vim to figure out how to check if the file was opened properly in hex mode or not. I would welcome patches or even shell commands I can execute to determine if the test passed! For instance, the commands you provided in issue #31 were excellent ways to test if the file was saved properly or not. Do you have any suggestions for me?

**Comment by mjsir911** [comment]
`diff` does seem to work, although the second autodetection test fails (same as problem with #31).

As for the tests; I definitely over-engineered the code a bit, but take a look at #34 and we can discuss more over there if need be.
