### ISSUE TITLE
Add help page

### ISSUE THREAD

**Issue by padde** [fidian/hexmode#4]
It's always good to have a help page which can be accessed from Vim. For info on how to create one, see http://learnvimscriptthehardway.stevelosh.com/chapters/54.html

I'd be happy to help, but won't be able to do it immediately.

**Comment by fidian** [comment]
Sounds like a good idea, but I too won't be able to do it right away.  I didn't know that help pages could be created in vim.  Really, this script isn't mine and I've just tried to give it a home on GitHub in the hopes that people would come by and help when and where they could, just like what you've done!

I'll try to get to this in the near future.  If you beat me to it, I will proofread and offer any assistance I can.

**Comment by fidian** [comment]
Hopefully that commit will provide enough of an overview.  I mostly just copied and pasted from the wiki.

**Comment by padde** [comment]
Wow, thanks for your work, looks great!
